export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_FOLLOWERS_DETAILS = 'GET_USER_FOLLOWERS_DETAILS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';
export const RESET_CURRENT_FETCHED_MEMBER = 'RESET_CURRENT_FETCHED_MEMBER';
export const VERYFY_FOLLOW_STATUS = 'VERYFY_FOLLOW_STATUS';
