export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_PROFILE_ERROR';
