export const POST_COMMENT_STARTED = 'POST_COMMENT_STARTED';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const RESTORE_COMMENT_TICK = 'RESTORE_COMMENT_TICK';