export const SET_RECOMMENDATIONS = 'SET_RECOMMENDATIONS';
export const SET_SEARCH_ITEMS = 'SET_SEARCH_ITEMS';
export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';
export const SET_SEARCH_STATE = 'SET_SEARCH_STATE';
