export const SHARE_POST_STARTED = 'SHARE_POST_STARTED';
export const SHARE_POST_SUCCESS = 'SHARE_POST_SUCCESS';
export const SHARE_POST_ERROR = 'SHARE_POST_ERROR';
export const SET_SHARE_POST_CONTENT = 'SET_SHARE_POST_CONTENT';
export const CLEAR_SHARE_POST_CONTENT = 'CLEAR_SHARE_POST_CONTENT';
