export const SIGNUP = 'SIGNUP';
export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_INPUT_CHANGED = 'SIGNUP_INPUT_CHANGED';
